/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rps;

import java.util.Random;

/**
 *
 * @author OmerFaruk
 */
public class RPSG extends javax.swing.JPanel {

    String computerPlay;
    int l = 0, w = 0, t = 0, i = 0;
    int gameNumber = 0;
    boolean Check = false;
    boolean ch1 = false;

    /**
     * Creates new form RPSG
     */
    public RPSG() {
        initComponents();
        GameCount.setVisible(true);
        Scissors.setVisible(false);
        Paper.setVisible(false);
        Rock.setVisible(false);
       
    }

    public void randomgenerator() {
        Random generator = new Random();
        int computerInt = generator.nextInt(3);

        switch (computerInt) {
            case 0:
                computerPlay = "R";
                break;
            case 1:
                computerPlay = "P";
                break;
            case 2:
                computerPlay = "S";
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tournemant = new javax.swing.JRadioButton();
        SingleGame = new javax.swing.JRadioButton();
        GameCount = new javax.swing.JTextField();
        totalWin = new javax.swing.JLabel();
        totalLose = new javax.swing.JLabel();
        totalTie = new javax.swing.JLabel();
        Rock = new javax.swing.JButton();
        Paper = new javax.swing.JButton();
        Scissors = new javax.swing.JButton();
        win = new javax.swing.JLabel();
        lose = new javax.swing.JLabel();
        tie = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Tournemant.setText("Tournemant");
        Tournemant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TournemantActionPerformed(evt);
            }
        });

        SingleGame.setText("Single Game");
        SingleGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleGameActionPerformed(evt);
            }
        });

        GameCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameCountActionPerformed(evt);
            }
        });

        totalWin.setText("total win:");

        totalLose.setText("total lose:");

        totalTie.setText("total tie:");

        Rock.setText("Rock");
        Rock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RockActionPerformed(evt);
            }
        });

        Paper.setText("Paper");
        Paper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaperActionPerformed(evt);
            }
        });

        Scissors.setText("Scissors");
        Scissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScissorsActionPerformed(evt);
            }
        });

        win.setText("              ");

        lose.setText("             ");

        tie.setText("              ");

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Rock --- Paper --- Scissors");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(totalWin, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalLose, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(win)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalTie, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(lose)
                        .addGap(145, 145, 145)
                        .addComponent(tie)
                        .addGap(144, 144, 144))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Tournemant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GameCount, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(708, 708, 708))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Rock, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Paper, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Scissors, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SingleGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(577, 577, 577))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rock, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Paper, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Scissors, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tournemant, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GameCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SingleGame, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(128, 128, 128)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(win)
                                        .addComponent(lose)
                                        .addComponent(tie))
                                    .addGap(16, 16, 16))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(75, 75, 75)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(totalWin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(totalLose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(19, 19, 19)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(totalTie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TournemantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TournemantActionPerformed
        SingleGame.setVisible(false);
        Tournemant.setVisible(false);
        ch1 = true;
        Rock.setVisible(true);
        Paper.setVisible(true);
        Scissors.setVisible(true);
    }//GEN-LAST:event_TournemantActionPerformed

    private void SingleGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleGameActionPerformed

        Tournemant.setVisible(false);
        GameCount.setVisible(false);
        Check = true;
        ch1 = true;
        Rock.setVisible(true);
        Paper.setVisible(true);
        Scissors.setVisible(true);
    }//GEN-LAST:event_SingleGameActionPerformed

    private void ScissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScissorsActionPerformed
        if (ch1 == true){
            randomgenerator();
            switch (computerPlay) {
                case "R":
                    l++;
                    break;
                case "P":
                    w++;
                    break;
                case "S":
                    t++;
                    break;
            }
            totalWin.setText("total win: " + w);
            totalLose.setText("total lose: " + l);
            totalTie.setText("total tie: " + t);
            if (Check == true) {
                Rock.setVisible(false);
                Scissors.setVisible(false);
                Paper.setVisible(false);
            }
            if ((w + l + t) == gameNumber) {
                Rock.setVisible(false);
                Paper.setVisible(false);
                Scissors.setVisible(false);
            }
        }
    }//GEN-LAST:event_ScissorsActionPerformed


    private void PaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaperActionPerformed
        if (ch1 == true){
            randomgenerator();
            switch (computerPlay) {
                case "R":
                    w++;
                    break;
                case "P":
                    t++;
                    break;
                case "S":
                    l++;
                    break;
            }
            totalWin.setText("total win: " + w);
            totalLose.setText("total lose: " + l);
            totalTie.setText("total tie: " + t);
            if (Check == true) {
                Rock.setVisible(false);
                Scissors.setVisible(false);
                Paper.setVisible(false);
            }
            if ((w + l + t) == gameNumber) {
                Rock.setVisible(false);
                Paper.setVisible(false);
                Scissors.setVisible(false);
            }
        }
    }//GEN-LAST:event_PaperActionPerformed

    private void RockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RockActionPerformed
        if (ch1 == true){
            randomgenerator();
            switch (computerPlay) {
                case "R":
                    t++;
                    break;
                case "P":
                    l++;
                    break;
                case "S":
                    w++;
                    break;
            }
            totalWin.setText("total win: " + w);
            totalLose.setText("total lose: " + l);
            totalTie.setText("total tie: " + t);
            if (Check == true) {
                Rock.setVisible(false);
                Scissors.setVisible(false);
                Paper.setVisible(false);
            }
            if ((w + l + t) == gameNumber) {
                Rock.setVisible(false);
                Paper.setVisible(false);
                Scissors.setVisible(false);
            }
        }
    }//GEN-LAST:event_RockActionPerformed

    private void GameCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameCountActionPerformed
        String number = GameCount.getText();
        gameNumber = Integer.parseInt(number);
        GameCount.setVisible(false);
    }//GEN-LAST:event_GameCountActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed

        GameCount.setVisible(true);
        SingleGame.setVisible(true);
        Tournemant.setVisible(true);
        totalLose.setText("total lose: ");
        totalWin.setText("total win: ");
        totalTie.setText("total tie: ");
        l = 0;
        w = 0;
        t = 0;
        i = 0;
        gameNumber = 0;
        Check = false;
        Rock.setVisible(false);
        Paper.setVisible(false);
        Scissors.setVisible(false);


    }//GEN-LAST:event_resetButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GameCount;
    private javax.swing.JButton Paper;
    private javax.swing.JButton Rock;
    private javax.swing.JButton Scissors;
    private javax.swing.JRadioButton SingleGame;
    private javax.swing.JRadioButton Tournemant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lose;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel tie;
    private javax.swing.JLabel totalLose;
    private javax.swing.JLabel totalTie;
    private javax.swing.JLabel totalWin;
    private javax.swing.JLabel win;
    // End of variables declaration//GEN-END:variables
}
